# Generated by Django 5.0.6 on 2024-08-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_image',
        ),
    ]
